CREATE SCHEMA IF NOT EXISTS public;

CREATE TABLE IF NOT EXISTS public.region
(
    id_region bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name varchar,
    CONSTRAINT region_pkey PRIMARY KEY (id_region)
);

