CREATE TABLE IF NOT EXISTS public.writer
(
    id_writer bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    first_name varchar,
    last_name varchar,
    region_id bigint,
    CONSTRAINT writer_pkey PRIMARY KEY (id_writer),
    CONSTRAINT writer_region FOREIGN KEY (region_id)
        REFERENCES public.region (id_region)
);