CREATE TABLE IF NOT EXISTS public.post
(
    id_post bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    content varchar,
    created bigint,
    updated bigint,
    writer_id bigint,
    constraint post_pkey PRIMARY KEY (id_post),
    CONSTRAINT writer_post FOREIGN KEY (writer_id)
        REFERENCES public.writer (id_writer)
);